feat(gitlab): Added changelog templates

diff --git a/git-toolkit.yml b/git-toolkit.yml
--- a/git-toolkit.yml
+++ b/git-toolkit.yml
@@ -48,3 +48,49 @@
     paths:
       - changelog.txt
     expire_in: 1 week
+
+.changelog:
+  variables:
+    CHANGELOG_FILE: "CHANGELOG.md"
+    TAG_QUERY: ""
+  image: registry.miquido.net/gitlab/miquido-chglog
+  script:
+    - /chglog/latest-tag.sh $TAG_QUERY > $CHANGELOG_FILE
+  tags:
+    - miquido
+    - docker
+  rules:
+    - if: $CI_COMMIT_TAG
+  artifacts:
+    expire_in: "1 week"
+    paths:
+      - $CHANGELOG_FILE
+
+.push-changelog:
+  stage: .post
+  image: frolvlad/alpine-bash
+  script:
+    - apk add git
+    - TXT_RED="\e[31m"
+    - |
+      if [ "$GITLAB_TOKEN" = "<ENTER_VAR>" ]; then
+        echo -e "${TXT_RED}Fatal: Missing GITLAB_TOKEN. \
+      Please setup GITLAB_TOKEN variable with token with write_repository rights"
+        exit 1
+      fi
+    - git remote set-url origin https://token:$GITLAB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
+    - git config --global user.name "Changelog-bot"
+    - git config --global user.email "Changelog-bot@miquido.com"
+    - git stash
+    - git checkout $CI_DEFAULT_BRANCH
+    - git pull
+    - git stash apply
+    - git add CHANGELOG.md
+    - |
+      git commit -m "chore(changelog): Changelog $CI_COMMIT_TAG [skip-ci]"
+      git push
+  tags:
+    - miquido
+    - docker
+  rules:
+    - if: $CI_COMMIT_TAG
