feat(git): more verbose logging

diff --git a/git-toolkit.yml b/git-toolkit.yml
--- a/git-toolkit.yml
+++ b/git-toolkit.yml
@@ -5,9 +5,17 @@
     - miquido
   stage: .post
   image: frolvlad/alpine-bash
+  variables:
+    GITLAB_TOKEN: "<ENTER_VAR>"
   before_script:
     - apk add git
   script:
+    - TXT_RED="\e[31m"
+    - |
+      if [ "$GITLAB_TOKEN" = "<ENTER_VAR>" ]; then
+        echo -e "${TXT_RED}Fatal: Missing GITLAB_TOKEN. \
+      Please setup GITLAB_TOKEN variable with token with write_repository rights"
+        exit 1
     - git tag -l | xargs git tag -d
     - git fetch origin 'refs/tags/*:refs/tags/*'
     - VERSION=$(git tag --sort=committerdate | { grep "[0-9]*.[0-9]*.[0-9]*$" || true; }| tail -1)
